[project]
name = "duck"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "logfire>=4.14.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
    "sqlalchemy>=2.0.44",
]
